NumPy - library used for numerical computations and array operations

In [37]:
#load the numpy library as np
import numpy as np

In [38]:
np.__version__

'1.26.4'

In [7]:
marks=[56,89,78]
total=[100,100,100]
#below element by element divsion does not work with lists
marks/total

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [8]:
stdnt_marks=np.array([56,89,78])
stdnt_marks

array([56, 89, 78])

In [9]:
#1D element
total=np.array([100,100,100])

In [11]:
ans=stdnt_marks/total
print(ans)

[0.56 0.89 0.78]


In [ ]:
#Functions for numpy array
stdnt_marks=np.array([56,89,78])
stdnt_marks

In [12]:
stdnt_marks.dtype #dtype-It is used to specify the type of data stored in an array or a variable. 

dtype('int32')

In [13]:
#dimension of array
stdnt_marks.ndim

1

In [14]:
#size of each element- refers to the total number of elements in the array.
stdnt_marks.size

3

In [15]:
#shape -  refers to the dimensions (rows and columns) of the array.
stdnt_marks.shape

(3,)

In [18]:
#indexing 2 dimensional data
data = np.array([[10,3],[15,2],[25,2],[30,3]],dtype='int32')
data

array([[10,  3],
       [15,  2],
       [25,  2],
       [30,  3]])

In [19]:
#2D arrays rows and columns
data[1,] #the elements/values in the first index will be printed

array([15,  2])

In [20]:
data[1,:] #This syntax explicitly specifies both the row and the column indices.The : is a slice notation indicating "all."

array([15,  2])

In [21]:
data[0:2,[0]]

array([[10],
       [15]])

In [22]:
data[2,1]

2

In [23]:
data.ndim

2

In [24]:
data.shape

(4, 2)

Introduction to NumPy Array

In [25]:
ones_arr=np.ones((3,3))
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
zero_arr=np.zeros((2,1))
zero_arr

array([[0.],
       [0.]])

In [ ]:
#The asarray() method in NumPy can be used to create an array from data that already exists
'''numpy.asarray() is a function that is essentially a more flexible version of numpy.array().
It is a convenient function to convert input to an array, but if the input is already an array, asarray does not make a copy.numpy.array() is a function to create an array from a given object (like a list or tuple).
If the input is already an array, it will make a copy of the array.'''
#convert list to array
x=[1,2,3]
a=np.asarray(x)
print(a)

In [29]:
x=[6,7,9]
a1=np.array(x)
print(a1)

[6 7 9]


In [28]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [30]:
#copy Array using numpy.copy()
#create a numpy array
a=np.array([[8,2,3],
           [4,7,6]])
#copy contents of a to b
b=a.copy()

#modify a
a[1,2]=13

#check if b has remained the same
print(a)
print(b)

[[ 8  2  3]
 [ 4  7 13]]
[[8 2 3]
 [4 7 6]]


In [31]:
#using numerical range arange()
arr=np.arange(0,20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [32]:
#importing numpy module
import numpy as np

#creating list
list1=[1,2,3,4]
list2=[5,6,7,8]
list3=[9,10,11,12]

#creating numpy array
sample_array=np.array([list1,
                       list2,
                       list3])
print("Numpy multi dimensional array in python\n",sample_array)

Numpy multi dimensional array in python
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
#print shape of the array
print("Shape of the array :", sample_array.shape)

Shape of the array : (3, 4)


In [34]:
import numpy as np
sample_array1= np.array([[0,4,2],
                         [3,4,5],
                         [23,4,5],
                         [2,34,5],
                         [5,6,7]])
print("Shape of the array:",sample_array1.shape)
print(sample_array1)

Shape of the array: (5, 3)
[[ 0  4  2]
 [ 3  4  5]
 [23  4  5]
 [ 2 34  5]
 [ 5  6  7]]


In [4]:
#import module
import numpy as np

#creating the array
sample_array1=np.array([[0,4,2]])
sample_array2=np.array([0.2,0.4,2.4])

#display data type
print("Data type of array1:",sample_array1.dtype)
print("Data type of array2:",sample_array2.dtype)

print(sample_array1)
print(sample_array2)


Data type of array1: int32
Data type of array2: float64
[[0 4 2]]
[0.2 0.4 2.4]


In [36]:
#numpy.arange(): This is an inbuilt NumPy function that returns evenly spaced values within a given interval
np.arange(1,20,2,dtype=np.float32)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32)

In [5]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [11]:
#using numerical range linespace()
#numpy.linspace(): This function returns evenly spaced numbers over a specified between two limits
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [12]:
import numpy as np
np.linspace(3.5,10,3,dtype=np.int32)

array([ 3,  6, 10])

In [13]:
import numpy as np
np.linspace(3.5,10,3)

array([ 3.5 ,  6.75, 10.  ])

In [14]:
#numpy.ones(): This function is used to get a new array of given shape and type,filled with ones(1)
import numpy as np
np.ones([4,3],dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
np.zeros([4,3],
         dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
import numpy as np
#create a 2-D array
array1=np.array([[2,4,6],
                 [1,3,5]])

#check the dimension of array1
print(array1.ndim)

#return total number of elements in array1
print(array1.size)

#return a tuple that gives size of array in each dimension
print(array1.shape)

#check the data type of array1
print(array1.dtype)

#use of itemsize to determine size of each array element of array1 and array2
print(array1.itemsize)

2
6
(2, 3)
int32
4


In [18]:
#providing two arange arguements
arr1=np.arange(start=1,stop=10,step=2)
print(arr1)

arr2=np.arange(start=1,stop=10)
print(arr2)

[1 3 5 7 9]
[1 2 3 4 5 6 7 8 9]


Basic Numpy operation

In [19]:
#Numpy ADD operator
#we can also use the add operator "+" to perform addition of two arrays
import numpy as np
a=np.array([10,20,100,200,500])
b=np.array([3,4,5,6,7])
print(a+b)

[ 13  24 105 206 507]


In [20]:
np.add(a,b)

array([ 13,  24, 105, 206, 507])

In [21]:
#Numpy subtract operator
a=np.array([10,20,100,200,500])
b=np.array([3,4,5,6,7])
np.subtract(a,b)

array([  7,  16,  95, 194, 493])

In [22]:
#Numpy multiply function
a=np.array([7,3,4,5,1])
b=np.array([3,4,5,6,7])
np.multiply(a,b)

array([21, 12, 20, 30,  7])

In [23]:
print(a*b)

[21 12 20 30  7]


In [24]:
#NumPy Divide function
a=np.array([7,3,4,5,1])
b=np.array([3,4,5,6,7])
np.divide(a,b)

array([2.33333333, 0.75      , 0.8       , 0.83333333, 0.14285714])

In [25]:
print(a/b)

[2.33333333 0.75       0.8        0.83333333 0.14285714]


In [26]:
#NumPy mod function
#We use both the functions to output the remainder of the division of two arrays
a=np.array([7,3,4,5,1])
b=np.array([3,4,5,6,7])
np.mod(a,b)

array([1, 3, 4, 5, 1])

In [27]:
a%b

array([1, 3, 4, 5, 1])

In [28]:
np.remainder(a,b)

array([1, 3, 4, 5, 1])

In [29]:
#Arithmetic operators with single dimensional array
#create two arrays using np.arange
a=np.arange(6)
b=np.arange(6,12)

#Element-wise arithmetic operations
result_addition=a+b
result_subtraction=a-b
result_multiplication=a*b
result_division=a/b
result_modulus=a%b
result_exponentiation=a**b
print(a)
print(b)
print("Addition:",result_addition)
print("Subtraction:",result_subtraction)
print("Multiplication:",result_multiplication)
print("Division:",result_division)
print("Modulus:",result_modulus)
print("Exponentiation:",result_exponentiation)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
Addition: [ 6  8 10 12 14 16]
Subtraction: [-6 -6 -6 -6 -6 -6]
Multiplication: [ 0  7 16 27 40 55]
Division: [0.         0.14285714 0.25       0.33333333 0.4        0.45454545]
Modulus: [0 1 2 3 4 5]
Exponentiation: [       0        1      256    19683  1048576 48828125]


In [31]:
#Arithmetic operators with multi dimensional array
c=np.arange(0,12).reshape(3,4)
d=np.ones((3,4))
print(c)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
result_addition1= c+d
result_subtraction1=c-d
result_multiplication1=c*d
result_division1=c/d
result_modulus1=c%d
result_exponentiation1=c**d
#print
print("Addition:",result_addition1)
print("Subtraction:",result_subtraction1)
print("Multiplication:",result_multiplication1)
print("Division:",result_division1)
print("Modulus:",result_modulus1)
print("Exponentiation:",result_exponentiation1)

In [32]:
#Arithmetic operators with multi dimensional array
c=np.arange(0,12).reshape(3,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
#Arithmetic operators with multi dimensional array
c=np.arange(0,12).reshape(2,4)
c

ValueError: cannot reshape array of size 12 into shape (2,4)

In [34]:
#matrix product 0*1=0,1*1=1,2*1=2 (0+1+2)=3
e=np.arange(0,9).reshape(3,3)
f=np.ones((3,3))
print(e)
print(f)
print(np.dot(e,f))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]


Matrix Product