#NumPy Arrays and Functions

###Demo 1: Matrix Product

In this demo, you will be shown how to implement Hill Cipher using matrix product.

### Question1: Perform Hill Cipher using matrix product

#### Description about Hill Cipher

'''
Hill Cipher is a polygraphic substitution cipher based on linear algebra.
Here the plain text is converted into encrypted form.
Each letter of plain text is represented by a number modulo 26.
Often the simple scheme A=0, B=1,....Z=25 is used
To encrypt a message, each block of n letters is multiplied by an invertible n × n matrix, against modulus 26
The matrix used for encryption is the cipher key, and it should be chosen randomly
Lets us take plain text = edurek and cipher key = [11 9
                                                     8 17]
Plain text is converted into 2×1 matrix format i.e. [e d] [u r] [e k]
Again plain text is converted into numbers i.e. [4 3] [20 11] [4 10]
So, encryption of hill cipher = (each column of plain text)*(key)*mod 26
'''

### Step 1: Import the libraries

In [4]:
import numpy as np

In [5]:
#A   B   C   D   E   F   G   H   I   J   K   L   M   N   O   P   Q   R   S   T   U   V   W   X   Y   Z
#0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25

### Step 2: Create numpy array a as first column of plain text and array b as key

In [6]:
a = np.array([4,3]) #  e d pair
b= np.array([[11,9],[8,17]]) #random values

### Step 3: Perform matrix product between array a and b

In [9]:
c=np.dot(a,b)  #[(4*11 , 4*9)(3*8, 3*17)] [(44+24),(36+51)]
c

array([68, 87])

### Step 4: Perform encryption of plain text using mod function

In [ ]:
h = np.mod(c,26) #68%26, 87%26
print("h=",h)

h= [16  9]


### Step 5: Create numpy array d of second column of plain text and array b as key

In [10]:
d = np.array([20,17]) #u r 

### Step 6: Perform matrix product between array d and b

In [12]:
f = np.dot(d,b)
f

array([356, 469])

### Step 7: Perform encyption of plain text using mod function

In [ ]:
h1=np.mod(f,26)
print("h1=",h1)

h1= [22  3]


### Step 8: Create a numpy array g of last column of plain text and array b as key

In [14]:
g = np.array([4,10]) #e,k

### Step 9: Perform matrix product between array g and b

In [15]:
j =np.dot(g,b)
j

array([124, 206])

### Step 10: Perform encyption of plain text using mod function

In [17]:
h2=np.mod(j,26) 
print("h2",h2)

h2 [20 24]


In [ ]:
'''h = 16,9 = q,j
   h1=  22,3 = w,d 
   h2=  20,24 = u,y
   therefore the text in encrypted = qjwduy

In [ ]:
Represent the matrix h, h1, h2 in alphabetic manner as explained above. So Plain Text in encypted format will be qjwduy

#### Conclusion: This code demonstrates how to perform matrix product