NumPy functions

In [3]:
#Universal functions : it operates on nd arrays. It performs elememt-wise array operations
import numpy as np
np.sqrt([1,4,9])

array([1., 2., 3.])

Type of universal functions: Math, Trignometric, Bit-twiddling, Comparison, Floating

In [4]:
#mod
import numpy as np
x=np.mod(np.arange(7),5)
print(x)

[0 1 2 3 4 0 1]


In [5]:
#log
import numpy as np
x=np.log([1,np.e,0]) #the natural logarithm of np.e (where np.e is a constant in NumPy representing Euler's number), the result will be 1.
print(x)

[  0.   1. -inf]


C:\Users\Shilpa R\AppData\Local\Temp\ipykernel_1396\3128514517.py:3: RuntimeWarning: divide by zero encountered in log
  x=np.log([1,np.e,0]) #the natural logarithm of np.e (where np.e is a constant in NumPy representing Euler's number), the result will be 1.


In [6]:
#bitwise and
import numpy as np
x=np.bitwise_and(9,10)
print(x)

8


In [7]:
#hypot
import numpy as np
Base=6
Height=4
Hypotenuse=np.hypot(Base,Height) #=  36+16=52 sqrt(52)
print(Hypotenuse)

7.211102550927978


In [8]:
#nan :The np.isnan() function checks for NaN(Not a Number)values, 
#in this case, it will return an array of booleans indicating whether each corresponding element in the input array x is NaN or not.
import numpy as np
x=np.log([(-1),1.,np.log(0)])#The natural logarithm of -1 is undefined, so it will result in a complex number.Log of 1 is zero and 0 is undefined
#LOG(-1)= undefined - not a number
#log(1) = 0- number
#log(0) = undefined - not a number
y=np.isnan(x)
print(y)

[ True False  True]


C:\Users\Shilpa R\AppData\Local\Temp\ipykernel_1396\1366652403.py:4: RuntimeWarning: divide by zero encountered in log
  x=np.log([(-1),1.,np.log(0)])#The natural logarithm of -1 is undefined, so it will result in a complex number.Log of 1 is zero and 0 is undefined
C:\Users\Shilpa R\AppData\Local\Temp\ipykernel_1396\1366652403.py:4: RuntimeWarning: invalid value encountered in log
  x=np.log([(-1),1.,np.log(0)])#The natural logarithm of -1 is undefined, so it will result in a complex number.Log of 1 is zero and 0 is undefined


Aggregate functions

In [9]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a.sum())
print(a.min())
print(a.max())
print(a.mean())
print(a.std())

15
1
5
3.0
1.4142135623730951


In [10]:
#In NumPy, the numpy.all() function returns True if all elements of the input array evaluate to True, and it returns False otherwise.
np.all([[True,False],[True,True]])

False

In [12]:
#example-2
arr = np.array([1, 2, 3, 4])
result = np.all(arr > 0)
print("Example 2:", result)

Example 2: True


In [15]:
np.all([[True,False],[True,True]],axis=0)

array([ True, False])

In [23]:
#any: In NumPy, the numpy.any() function is used to check if any element in the input array evaluates to True. 
#It returns True if at least one element is True, and False otherwise.
import numpy as np

# Example 1
arr1 = np.array([False, False, False])
result1 = np.any(arr1)
print("Example 1:", result1)  

# Example 2
arr2 = np.array([True, False, False])
result2 = np.any(arr2)
print("Example 2:", result2)

arr3 = np.array([0, 0, 0, 4])
result3 = np.any(arr3)
print("Example 3:", result3) 

# Example 4
arr4 = np.array([0, 0, 0])
result4 = np.any(arr4)
print("Example 4:", result4) 

Example 1: False
Example 2: True
Example 3: True
Example 4: False
