

## Demo 2: Array Creation And Manipulation


In [ ]:
#Reshaping of an array
import numpy as np   #Importing library
a = np.array([3,6,9,12,15,96])
print("Shape of a:",a.shape)

b = a.reshape(2,3)

print(b)
print("Shape of b:",b.shape)

#a=np.array([3,6,9,12,63])
#b = a.reshape(2,2)
#print(b) #Error ! can not reshape

In [ ]:
#ravel function - used to convert 2D array to 1D
import numpy as np

# Creating a 2D array
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# Using ravel to flatten the array
flattened_array = np.ravel(original_array)

print("Original array:")
print(original_array)

print("\nFlattened array:")
print(flattened_array)

In [ ]:
#Example-2 ravel() with 3D(nd) array
import numpy as np

# Creating a 3D array
three_d_array = np.array([[[1, 2, 3], [4, 5, 6]],
                          [[7, 8, 9], [10, 11, 12]],
                          [[13, 14, 15], [16, 17, 18]]])

# Using ravel to flatten the 3D array
flattened_array = np.ravel(three_d_array)

print("Original 3D array:")
print(three_d_array)

print("\nFlattened array:")
print(flattened_array)


In [ ]:
#transpose
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.transpose(a)
print('Original','\n','Shape',a.shape,'\n',a)
print('Expand along columns:','\n','Shape',b.shape,'\n',b)

In [1]:
#Joining arrays - Concatenate()
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.concatenate((arr1, arr2), axis=None)
print(result)

[1 2 3 4 5 6]


In [2]:
#axis=0
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])
result = np.concatenate((arr1, arr2), axis=0)
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [3]:
#axis=1
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])
result = np.concatenate((arr1, arr2), axis=1)
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#Joining arrays
import numpy as np

arr1 = np.array(( 1, 2, 3 ))
print ("1st Input array : \n", arr1) 
  
arr2 = np.array(( 4, 5, 6 ))
print ("2nd Input array : \n", arr2) 
  
#Verticle stacking
out_arr = np.vstack((arr1, arr2))  #Normal Stacking
print ("Output verticle stacked array:\n ", out_arr)

#Horizontal stacking(Concatenation)
out_arr = np.hstack((arr1, arr2)) 
print ("Output horizontal stacked array:\n ", out_arr)

In [ ]:
arr1 = np.array([[10,20,30],[100,200,300]])
print ("1st Input array : \n", arr1) 
  
arr2 = np.array([[40,50,60],[400,500,600]])
print ("2nd Input array : \n", arr2) 

out_arr = np.vstack([arr1, arr2])  
print ("Output horizontal stacked array:\n ", out_arr)

In [ ]:
#Fancy Indexing, we can pass array of indices to access multiple array values
a=np.array([3,78,23,12,56,96,78,25,34,78,14,19])
print(a[10])  #Normal indexing

ind=np.array([[3,4],[7,10]])
print(a[ind]) #Fancy indexing


Splitting Arrays

In [4]:
#split(): np.split function is used to split an array into multiple subarrays along a specified axis
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
result = np.split(arr, 3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [5]:
#hsplit(): The np.hsplit function is used to horizontally split an array into multiple subarrays.
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

result = np.hsplit(arr, 3)
print(result)
# Output: [array([[1],
#                 [4]]), array([[2],
#                                 [5]]), array([[3],
#                                                 [6]])]


[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [6]:
#vsplit(): The np.vsplit function is used to vertically split an array into multiple subarrays.
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

result = np.vsplit(arr, 2)
print(result)

[array([[1, 2, 3]]), array([[4, 5, 6]])]
